### ISSUE TITLE
Scenario Outline and step variables not working

### ISSUE THREAD

**Issue by simi823** [ndmanvar/Python-Behave-Selenium#3]
Hi Neil,

Was testing this out with an example of one of our projects. I tried using a Scenario Outline but it failed when it tried to get the url. Then I broke it up in individual tests like so:
Scenario: Visit Alabama Autos page and check title
    Given I am testing a Desktop browser
    When I visit "http://autos.al.com/"
    Then it should have a title "New and Used Cars in Alabama"

Scenario: Visit Cleveland Autos page and check title
    Given I am testing a Desktop browser
    When I visit "http://autos.cleveland.com/"
    Then it should have a title "New and Used Cars in Cleveland"

Scenario: Visit GulfLive Autos page and check title
    Given I am testing a Desktop browser
    When I visit "http://autos.gulflive.com/"
    Then it should have a title "New and Used Cars in Gulf Coast"

The step definitions are as follows:
from selenium import webdriver
from pages.main import AutosHomePage
from features.browser.browsers import make_browser

@given('I am testing a Desktop browser')
def step_impl(context):
  context.browser = make_browser(context.name)

@when('I visit "<browser_page>"')
def step_impl(context, browser_page):
  context.browser.get(browser_page)
  context.page = AutosHomePage(context.browser)

@then('it should have a title "<page_title>"')
def step_impl(context, page_title):
  context.page.assert_page_title(page_title)

The step for "When I visit ..." does not like the browser_page parameter like I've been using it in my behave tests. The same goes for the "Then it should have a title..." It comes out as step definitions as undefined. 

However, when I hard code the full URL and title name in a step like so:
@when(u'I visit "http://autos.al.com/"')
def step_impl(context):
  context.browser.get("http://autos.al.com/")
  context.page = AutosHomePage(context.browser)

@then('it should have a title "New and Used Cars in Alabama"')
def step_impl(context):
  context.page.assert_page_title("New and Used Cars in Alabama")

Then it works.

Can the parameters option be implemented. All of our tests have these data tables using Scenario Outlines.

**Comment by simi823** [comment]
Never mind... I see the issue. Sorry!!!

**Comment by ndmanvar** [comment]
@simi823 what was the issue?

**Comment by simi823** [comment]
Doh!! I had <parameter> in the step definition instead of {parameter} !!!
